---
# .pre-commit-config.yaml
# ========================
#
# pre-commit clean
# pre-commit install
# pre-commit install-hooks
#
# precommit hooks installation
#
# - pre-commit autoupdate
#
# - pre-commit run black
#
# continuous integration
# ======================
#
# - pre-commit run --all-files
#

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-merge-conflict
      - id: sort-simple-yaml
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: ["--fix=lf"]
        description: Forces to replace line ending by the UNIX 'lf' character.
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: no-commit-to-branch
        args: [--branch, master]
      - id: check-yaml
      - id: check-json
        files: ^tests/app/
      - id: pretty-format-json
        args: ["--no-sort-keys", "--autofix"]
        files: ^tests/app/

  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
      - id: black
        language_version: python3.9

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
    - id: bandit
      description: Security oriented static analyser for python code
      exclude: tests/|scripts/
      args:
        - -s
        - B101

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.3
    hooks:
      - id: vulture
        description: Find dead Python code
        entry: vulture
        args: [
            "--min-confidence", "90",
            "--exclude", "tests,env",
            "--ignore-names", "einfo,task_id,retval,logger,log_method,exc,args,status",
            ".",
        ]
        language: system
        types: [python]

  -   repo: https://github.com/codespell-project/codespell
      rev: v2.1.0
      hooks:
      -   id: codespell
          name: codespell
          description: Checks for common misspellings in text files.
          entry: codespell -L som
          language: python
          types: [text]

  -   repo: https://github.com/asottile/pyupgrade
      rev: v2.29.0
      hooks:
      -   id: pyupgrade
